baseURL: "https://Andreapm1977.github.io/"
title: Andrea Piano Mortari
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 1
        - name: Projects
          url: projects/
          weight: 2
        - name: Teaching
          url: teaching/
          weight: 3

params:
    description: "I am an Assistant Professor of Economics at Tor Vergata University of Rome. My main interests are in micro health econometrics, microsimulation and healthcare policy."
    author: Andrea Piano Mortari
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Andrea Piano Mortari
          subtitle: "I am an Assistant Professor of Economics at Tor Vergata University of Rome. My main interests are in micro health econometrics, microsimulation and healthcare policy."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Prof. Andrea Piano Mortari
          buttons:
            - name: Papers
              url: papers/
            - name: Projects
              url: projects/
            - name: Teaching
              url: teaching/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:andrea.pianomortari@uniroma2.eu
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=VsruSUcAAAAJ&hl=it
        - name: Orcid
          url: https://orcid.org/0000-0002-7220-2352
        - name: GitHub
          url: https://github.com/Andreapm1977
        - name: BlueSky
          url: https://bsky.app/profile/apmecon.bsky.social

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Andrea Piano Mortari"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
